#----------------------------------------------------------------------------
# Python.
#----------------------------------------------------------------------------
ansible_python_interpreter: "/usr/bin/python"

#----------------------------------------------------------------------------
# Common Bitbucket Felix Project SSH URL
#----------------------------------------------------------------------------
felix_git_root: "ssh://git@git.rakuten-it.com:7999/felix"

#----------------------------------------------------------------------------
# Repository for Ansible Common
#----------------------------------------------------------------------------
ansible_common_repo: "felix-ansible-common"
