#----------------------------------------------------------------------------
# Key file that Ansible is using to SSH connect to remote servers. For this
# to work properly remote servers must be configured to allow passwordless
# connection with this key. On controll host all remote hosts' finger keys
# should be already in known_hosts file.
#----------------------------------------------------------------------------
ansible_ssh_private_key_file: "~/.ssh/id_rsa"

#----------------------------------------------------------------------------
# User name to be used with the key above.
#----------------------------------------------------------------------------
ansible_user: "felixuser"
