#----------------------------------------------------------------------------
# Directory that contains all Ansible custom facts files.
#----------------------------------------------------------------------------
felix_remote_ansible_facts_path: "/home/felixuser/.ansible-facts"

#----------------------------------------------------------------------------
# Maven repository for downloading binary files from. (All jars is migrated to nexus 3)
#----------------------------------------------------------------------------
felix_remote_maven_repository: "http://dev-qcmdaci101z.dev.jp.local:8082/repository/felix"


#----------------------------------------------------------------------------
# Nexus3 Maven repository for downloading binary files from.
#----------------------------------------------------------------------------
felix_remote_maven_repository_nexus3: "http://dev-qcmdaci101z.dev.jp.local:8082/repository/felix"