#----------------------------------------------------------------------------
# All applications' versions are listed here for better readability.
#
# A `deployed` variable must contain a list of versions that are meant to
# be deployed. In other words - when script finish successfully, all (and
# only) versions listed will be deployed.
#----------------------------------------------------------------------------
app_versions:
  deployed:
    - "1.2.0"
  running: "1.2.0"
  instances: 1
