#----------------------------------------------------------------------------
# Import Ansible Common.
#----------------------------------------------------------------------------
- name: "Import Ansible Common"
  include: "import-ansible-common.yml"