#----------------------------------------------------------------------------
# Default logging level for felix application.
#----------------------------------------------------------------------------
app_log_level: "info"

#----------------------------------------------------------------------------
# Spring Boot Admin Setting
#----------------------------------------------------------------------------
spring_admin:
  url: "http://wfelix201z.prod.jp.local:7999"
  username: "{{vault['spring_admin']['username']}}"
  password: "{{vault['spring_admin']['password']}}"

#----------------------------------------------------------------------------
# Authentication keys.
#----------------------------------------------------------------------------
felix_auth_keys:
    test_send_manager: "{{vault['auth_keys']['test_send_manager']}}"

#----------------------------------------------------------------------------
# Data store config.
#----------------------------------------------------------------------------
felix_persistence:
  url:
   scenario: "jdbc:mysql://dm-felix201z.prod.jp.local:3301/felix_scenario_01"
  access:
    common:
      user: "{{vault['db2']['common']['user']}}"
      password: "{{vault['db2']['common']['password']}}"
  show_jpa_query: false

#----------------------------------------------------------------------------
# Proxy config. Used for accessing internal APIs.
#----------------------------------------------------------------------------
felix_proxy:
  default:
    host:
    port:

#----------------------------------------------------------------------------
# Messaging broker config.
#----------------------------------------------------------------------------
felix_mq:
  connection:
    addresses:
      - "amqfelix101z.prod.jp.local:5672"
      - "amqfelix102z.prod.jp.local:5672"
      - "amqfelix103z.prod.jp.local:5672"
    user: "{{vault['mq']['user']}}"
    password: "{{vault['mq']['password']}}"
  prefix: "felix."
  channels:
    kick_test_send_finished: "kick-test-send-finish"
    test_send_finished: "test-send-finished"
    test_send_error: "test-send-error"
    kick_test_send: "kick-test-send"
    error_channel: "error"
    publish_notification: "publish-notification"

#----------------------------------------------------------------------------
# Internal APIs' URLs.
#----------------------------------------------------------------------------
felix_api:
  job_data_keeper:
    get_complete_job: "http://api.core.felix.prod.jp.local/v1.0/jobs/get"
